sonar.projectKey=Mini-HSM
sonar.projectName=Mini-HSM
sonar.sourceEncoding=UTF-8

sonar.sources=crates,tools
sonar.exclusions=**/*_test.rs,**/tests/**/*.rs

sonar.language=rust
sonar.rust.lcov.reportPaths=lcov.info
sonar.rust.clippy.reportPaths=clippy-report.json
sonar.sarifReportPaths=cargo-audit.sarif